- src/Components/ChartCard/ChartCard.js
- src/Components/NumberData/NumberData.js
- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SigTable/SigTable.js
- src/Components/StatusCard/StatusCard.js
fixes https://issues.redhat.com/browse/YARA-108
> System and matched counts that can get big should be local formatted 🦤

- src/Components/SigDetailsTable/SigDetailsTable.js
- src/operations/queries.js
fixes https://issues.redhat.com/browse/YARA-106
> Swaps hostname for insightsId

- build/messages/src/Messages.json
- locales/translations.json
- src/Components/SigTable copy/SigTable.js
- src/Components/StatusCard/StatusCard.js
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Components/SysTable/SysTable.js
- src/Components/SysTable/SysTable.scss
- src/Messages.js
- src/Routes.js
- src/Routes/Signatures/Routes.js
- src/Routes/Systems/Details.js
- src/Routes/Systems/Details.scss
- src/Routes/Systems/Routes.js
- src/Routes/Systems/Systems.js
- src/operations/queries.js
- src/store/cache.js
fixes https://issues.redhat.com/browse/YARA-72
still waiting for clarification on a few points... total match/match details, but those will be lil change compared to this body of work, advocate merging this in soonest for funzies
> Adds /systems and /systems/system_name pages

- locales/translations.json
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Messages.js
- src/operations/queries.js
Feel free to reject this one if you don't think its worth it ... but I think its nice to have :smiley_cat:
> Add scan metadata to systems details table

- src/AppEntry.js
fixes https://issues.redhat.com/browse/YARA-152
> Updates mda app to support chrome lnav 

- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Routes/Systems/Details.js
- src/operations/queries.js
This attempts to align the inconsistent dates listed in this ticket. https://issues.redhat.com/browse/YARA-217
> Fix inconsistent date-times

- src/Components/SharedComponents/EmptyAccount.js
- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/StatusCard/StatusCard.js
- src/Messages.js
- src/Routes/Signatures/Details.js
- src/Routes/Signatures/Signatures.js
- src/Routes/Systems/Systems.js
Empty account state is handled: 
Signatures:
Signature details: 
Systems:
> YARA-214 Guide brand new users to MD setup docs

- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SigTable/SigTable.js
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Components/SysTable/SysTable.js
https://issues.redhat.com/browse/YARA-216
The issue was caused by the page number not being reset upon filtering.
> Fix filter for item not on current page

- src/Components/SharedComponents/EmptyAccount.js
- src/Routes/Signatures/Signatures.js
Removes new lines and spaces from doc link
> Remove new lines from doc url

- src/Components/ChartCard/ChartCard.scss
- src/Components/StatusCard/StatusCard.js
- src/Components/StatusCard/StatusCard.scss
- src/Components/StatusLabel/StatusLabel.js
- src/Routes/Signatures/Signatures.js
- src/Routes/Systems/Systems.js
Closes [YARA-280](https://issues.redhat.com/browse/YARA-280)
> fix: responsive layout and labels

- src/Components/SharedComponents/EmptyAccount.js
- src/Routes/Signatures/Signatures.js
updates version to 2022 to links resolve
> update docs urls

- src/App.scss
- src/Components/SysTable/SysTable.js
- src/Components/SysTable/constants.js
- src/Components/SysTable/hooks.js
- src/operations/queries.js
Closes [YARA-177](https://issues.redhat.com/browse/YARA-177)
> Adds tag filtering to SysTable

- src/Components/SysTable/constants.js
- src/Routes/Systems/Details.js
- src/operations/queries.js
https://issues.redhat.com/browse/YARA-373
> Differentiate between systems with the same hostname

- locales/translations.json
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Components/SysTable/constants.js
- src/Messages.js
- And adjust messaging for not matched systems
> Fix missed occurrence of using system uuid instead of name

- deploy/frontend.yaml
Per containerization [documentation](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=RHIF&title=Containerizing+your+application+and+deploying+on+Ephemeral+environments) 
This adds a frontend-yml file to malware
> adds frontend.yml for containerization

- locales/translations.json
- src/Messages.js
- src/Routes/Signatures/Details.js
- src/Routes/Signatures/Details.scss
* Fixes https://issues.redhat.com/browse/YARA-426
> Re-arrange signature metadata layout

- src/Components/SysTable/SysTable.js
- src/Components/SysTable/SysTable.scss
- src/Components/SysTable/constants.js
* https://issues.redhat.com/browse/YARA-442
* https://issues.redhat.com/browse/YARA-441
* Changed systable column widths and increased system name font size
> UI changes from QA feedback

- .eslintrc.yml
- .gitignore
- .travis.yml
- babel.config.js
- config/cypress.webpack.config.js
- coverage.sh
- cypress.config.js
- cypress/support/commands.js
- cypress/support/component-index.html
- cypress/support/component.js
- package-lock.json
- package.json
- src/Components/MessageState/MessageState.cy.js
Initializes cypress with basic test
> feat(Cypress): Initialize cypress in malware

- src/App.js
- src/AppEntry.js
- src/Routes/NoPermissionsPage/NoPermissionsPage.js
Replaces insights.chrome with useChrome
> chore(RHIF-127): adopt useChrome

- src/Components/ChartCard/ChartCard.js
- src/Components/ChartCard/ChartCard.scss
* https://issues.redhat.com/browse/YARA-587
> Ensure tooltips align with correct bar in system scan chart

- src/Routes.js
As in accordance to these mocks, this PR adds zero state to Malware,  https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit#heading=h.1hvxoje16w3i  https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect   https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD
> feat(RHIN-830): Add ZeroState to Malware

- src/Routes/Signatures/Signatures.js
- src/Routes/Systems/Systems.js
https://issues.redhat.com/browse/YARA-630
> fix(YARA-630): add conditionals to alerts

- src/Components/SysTable/Helpers.js
- src/Components/SysTable/SysTable.js
- src/Components/SysTable/constants.js
- src/Components/SysTable/matchFilter.js
- src/operations/queries.js
Ticket: https://issues.redhat.com/browse/YARA-621 
This adds the match filter from signature table and makes it default on page load
> Feat(YARA-621): Add match filter to systems table

- src/Components/SigTable/SigTable.js
- src/Components/SysTable/Helpers.js
- Always display the Reset filters button in SigTable & SysTable filter chips
- Adds All as a filter chip in SigTable
> fix(RHINENG-802): Always display Reset filters button

- src/Components/SysTable/SysTable.js
- src/Components/SysTable/constants.js
https://issues.redhat.com/browse/ESSNTL-3719
> feat(ESSNTL-3719): Add Inventory group filter and column

- src/Components/SysTable/SysTable.js
- src/Components/SysTable/constants.js
- src/operations/queries.js
- Requests the groups data from the backend
- Populates the Group column from the data
- Adjusts some column widths so all the data better in a row
> fix(ESSNTL-4820): Populate the host group column

- src/App.scss
- src/Components/ChartCard/ChartCard.js
- src/Components/Common.js
- src/Components/Loading/Loading.js
- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SigTable/SigTable.js
- src/Components/StatusCard/StatusCard.js
- src/Components/StatusCard/StatusCard.scss
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Components/SysTable/SysTable.scss
- src/Routes.js
- src/Routes/Signatures/Details.js
- src/Routes/Signatures/Details.scss
- src/Routes/Signatures/Signatures.js
- src/Routes/Systems/Details.js
- src/Routes/Systems/Details.scss
- src/Routes/Systems/Systems.js
- src/operations/queries.js
There are a lot of items under https://issues.redhat.com/browse/RHINENG-1217 so it will be split into multiple PRs.
1. All pages
- 1. Page titles are 28px, but should be 24px
- 2. Skeleton tables are misaligned
2. Signatures page
- 1. Question mark icon next to the page header should be 16px not 28px
- 2. Question mark icon should show pointer cursor on hover
- 3. "Matched signatures" text does not include breakpoint between words
3. Systems page
- 1. Chart card should have only one loader, but has two
- 2. Table items are vertically misaligned
4. Signature detail page
- 1. Title labels are vertically misaligned
- 2. Icon and text under "Matched systems" has incorrect color, should use #C9190B (icon) and #A30000 (text)
- 3. "Affected systems" text should have 20px, not 28px
- 4. Total …
> Various UI improvements

- src/Components/SysTable/hooks.js
- src/operations/queries.js
Relates to https://issues.redhat.com/browse/ESSNTL-4820.
> fix(ESSNTL-4820): Filtering systems on host group name

- src/Components/SysTable/SysTable.js
- src/Components/SysTable/hooks.js
- src/operations/queries.js
Requires API changes to be merged first before this will work.
> feat: Filter systems on OS

- src/Components/SigTable/SigTable.js
- src/Components/StatusCard/StatusCard.js
Implements the checkbox for the 'Signatures enabled in malware analysis' filter in this mockup: https://www.sketch.com/s/ba054462-18d9-45b4-b6e1-0f58582fcf60/a/oMMGzp5
> fix: use checkbox for signatures enabled/disabled filter

- src/Components/SharedComponents/EmptyAccount.js
- src/Routes/Signatures/Signatures.js
https://issues.redhat.com/browse/RHINENG-1465 
This PR just updates the old malware links
> fix(RHINENG-1465): update malware doc links

- src/Components/SigTable/SigTable.js
- src/Components/StatusCard/StatusCard.js
- src/Messages.js
- src/Routes/Signatures/Details.js
- src/operations/mutations.js
- src/operations/queries.js
- Ensure matched disabled rules show for matched filter
- Set 'signatures included ...' as first filter item
- Lessen column width of signature title
> Changes for RHINENG-2175

- locales/translations.json
- src/Components/Common.js
- src/Components/SigTable/SigTable.js
- src/Messages.js
- src/Routes/Signatures/Details.js
- for example, if user lacks permission to perform mutation
> Display useMutation errors as notifications

- config/prod.webpack.config.js
Adds prod webpack check for stable and preview code.
> chore: differentiate stable and preview code in prod env:

- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SigTable/SigTable.js
- src/Components/SysDetailsTable/SysDetailsTable.js
The padding via the TableToolbar is required to avoid colliding with the "lightbulb"
**Before:**
**After:**
> fix(Tables): RHINENG-2325 - Add padding to footer via TableToolbar

- src/Routes/Systems/Details.js
- src/Routes/Systems/Details.scss
Simple change.  Is this what you are looking for Samuel?
Before: 
After:
> fix(RHINENG-2791): System UUID font style to match inventory

- src/Components/SysDetailsTable/SysDetailsTable.js
> fix(RHINENG-2792): Add filter chips to system detail table

- src/Routes.js
This updates zero state in malware to use the updated version of the fed mod, and to make the call for ONLY RHEL systems, as opposed to ALL systems
> feat(RHINENG-5920): Update zero state call

- src/Components/Common.js
Updates the doc links with new 1-latest subpath
> chore(RHINENG-7106): update doc links with 1-latest

- package.json
- src/Components/SysTable/Helpers.js
- src/Components/SysTable/Helpers.test.js
- src/Components/SysTable/SysTable.js
- src/Components/SysTable/hooks.js
This fixes the OS filter to API filter conversion.
**How to test:**
1) Open the Malware "Systems" page
2) Try filtering systems by "Operating Systems"
> fix(SysTable): RHINENG-10810 - Fix OS filter conversion

- src/Components/SigDetailsTable/SigDetailsTable.js
Some fixes for the signatures details group/workspace filter
> fix(bug): sig table workspace filter fix

- src/Components/SigDetailsTable/Columns.js
- src/Components/SigDetailsTable/NewSigDetailsTable.js
- src/Components/SysDetailsTable/Columns.js
- src/Components/SysDetailsTable/NewSysDetailsTable.js
This PR shouldn't change any functionality. Simply check that columns still work in the Signature Details and Systems Details Tables. This will only work with the malware matches feature flag.
> refactor: Refactor columns in details tables

- src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
- src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
- src/Components/TableComponents/MatchedDateColumn.js
- src/Components/TableComponents/NewMatchesTableRow.js
- src/Components/helpers.js
This updates the dates matched column in sig/sys details tables. Whenever the dropdown, inside the table thats nested in the expanded rows, is set to Not Reviewed, the Dates matched column should be blue, and display a bell.
Mocks:
PR:
> feat(RHINENG-11705): Update Data column with dropdownValue

- src/Components/TableComponents/NewMatchesTable.js
- src/Components/TableComponents/NewMatchesTableRow.test.js
The new matches table should update the 'Dates matched' column header to 'Match date'
> fix(RHINENG-11862): Update column header to 'Match date'

- src/Components/SigDetailsTable/Columns.js
- src/Components/SigDetailsTable/SigDetailsTable.js
- src/Components/SigDetailsTable/SigDetailsTableBody.js
- src/Components/SigDetailsTable/__tests__/SigDetailsTable.tests.js
- src/Components/SigDetailsTable/__tests__/sigDetailsTable.fixtures.js
- src/Components/SysDetailsTable/Columns.js
- src/Components/SysDetailsTable/SysDetailsTable.js
- src/Components/SysDetailsTable/SysDetailsTableBody.js
- src/Components/SysDetailsTable/__tests__/SysDetailsTable.tests.js
- src/Components/SysDetailsTable/__tests__/sysDetailsTable.fixtures.js
- src/Components/TableComponents/DetailsTableHeader.js
- src/Components/TableComponents/NewMatchesTable.js
- src/Components/constants.js
- src/Components/hooks/__tests__/useMalwareSearchParams.tests.js
- src/Components/hooks/useMalwareSearchParams.js
- src/operations/queries.js
To test:
- Navigate to Signature/Systems
- Select an Affected system/Matched signature
- Apply filters, remove filters, load page with params in the url
Try everything you can to break this. Filtering should act as it normally does.
> feat(RHINENG-11149): Add url search params
