src/Components/Common.js
src/Components/SigDetailsTable/SigDetailsTable.js
src/Components/SysDetailsTable/SysDetailsTable.js

Having a bit of a test here and looking for feedback.  Seeing the metadata displayed just as string looked a bit blech.  Would look much better if it were expanded into its component fields, like in the screenshot!  However my Javascript foo is weak (or more like its too Python-ish) and I'm sure there is a much more Javascript-ish or React-ish way of implementing this, so feedback is most welcome.  Allen, you also don't seem to be fan of 'if' statements so I tried writing one of the functions without 'ifs'.  Looks a bit iffy though.

Expand match metadata

---

src/Components/Common.js

Converted the function to having if statements :scream: Much easier for this python programmer to read it.  In the screenshot below, the circle with the metadata I let the scan finish before uploading, but the circle without the metadata, I killed the process before the scan had finshed, so it wasn't able to collect metadata about the process.

Add checks to parsing metadata in case fields are missing

---

src/Components/Common.js

The missing metadata may not be because the Source is missing.  Customer might have set metadata=False in config file.

Change wording when no metadata available for a scan match

---

src/Components/SigTable/SigTable.js

https://issues.redhat.com/browse/YARA-240
Fixes the signature count sort on the signature page.  This was caused by the removal of the disabled column.

Fix system sort on signature page

---

src/Components/SysDetailsTable/SysDetailsTable.js

https://issues.redhat.com/browse/YARA-241
The json.parse was failing on some match metadata because of errant new lines.

Fix match detail card not expanding

---

src/Components/ChartCard/ChartCard.js

https://issues.redhat.com/browse/YARA-248
Numbers above 1000 were showing up as NaN because they were being double formatted.  The first format added a comma and the second format then failed because it expected a number, not a string.

Fix counts over 1000 showing as NaN

---

src/operations/queries.js

Previously we were using the fuzzy search match to retrieve a signature for the signature details page.  The signature detail page corresponds to an exact signature. Therefore we do an exact match.

Match signature name exactly on signature detail page

---

.eslintrc.yml
src/App.js
src/AppEntry.js
src/Components/SysTable/SysTable.js
src/Routes/Systems/Systems.js
src/store/cache.js

1. Enables MSSQL and AAP filters. We need to send **insights-mssql-system** and **insights-ansible-system** with the Appollo client request headers to filter by respective new filters. 
2. On stage/beta env, systems table is not reacting to global filter changes. This is fixed by storing changed global filters in Appollo client cache and providing those filters into customFilters prop of the InventoryTable component to force the table reload new data. According to docs, saving any data type to that cache is safe.
3. Fixes Lint configuration and errors.

Enable mssql app filter

---

src/Routes.js
src/Routes/TemporaryBetaPage/TemporaryBetaPage.js

Ticket: [ESSNTL-3360](https://issues.redhat.com/browse/ESSNTL-3360).
Prod-stable should contain only a page redirecting to /beta enviroment, this is a workaround to fix a missing feature in Insights Chrome, where clicking app link with beta chip feature should display modal with button to navigate to prod/beta. This modal is not always launched and could cause "Something went wrong" page. This PR fixes this by copying the modal contents into prod/stable as a singular page which serves as a fallback when modal is not shown. This is a temporary solution until Malware is launched into prod/stable completely.
Mockups: https://www.sketch.com/s/e7ea499d-f677-45be-aba7-a3a268fbe992/a/KvevQZ1 the modal contents should be moved into a page.
Malware app is currently not in prod-stable navigation …

Add temporary /beta redirect page to prod-stable

---

package-lock.json
package.json

Associated Jira ticket: https://issues.redhat.com/browse/RHIF-111
This aligns the version of `redux` and `react-redux` libraries to the ones in insights-chrome.

fix(Shared dependencies): Align versions of redux

---

src/Components/SigTable/SigTable.js

Added a backend option to sort last match with nulls last which should make a lot more sense.

Use nulls last match sorting

---

src/Components/SigDetailsTable/SigDetailsTable.js
src/Components/SigTable/SigTable.js

This PR originally used the tabletools PR from frontend components, but that has since been removed. Now this PR adds logic to the sorting so that when there are no systems on the table, sorting is disabled. 
To test simply navigate to the three tables within malware and get the table to render no systems. 
Then make sure sorting is disabled. 
This PR has to do with this ticket: https://issues.redhat.com/browse/YARA-395 , the ticket is fairly old, and the majority of the items it addresses are gone/ already reworked. This is the last of the items.
P.S I also added some formatting changes in one of the files just for easier readability

feat(YARA-395): TableTools Sorting rework 

---

src/Components/SysTable/constants.js

Implements https://issues.redhat.com/browse/ESSNTL-3719.
- make `/malware/systems`, Systems table render the Group column as a plain text
- make the column also sortable.
Navigate to /malware/systems, and make sure you are able to sort by the Group column, and also the group names are rendered as a plain text, not links.

fix(ESSNTL-3719): Make the group column sortable

---

src/Components/SigTable/SigTable.js

- Resets SigTable pagination whenever the filters change
- Correctly sets selectedSigs when SigTable rows are selected/unselected
- Apply secondary orderBy variable of NAME_ASC to table rows to add more determinism to their order

Fixes for RHINENG-2254

---

locales/translations.json
src/Components/SigTable/SigTable.js
src/Messages.js
src/Routes/Signatures/Details.js

(Basically, disabled signatures can't be matched, which is done in the backend)
- fix the chips for enabled/disabled filters
- display N/A for disabled rule stats
- initial filter state is just Matched

Changes after revisiting RHINENG-2175

---

locales/translations.json
src/Components/Common.js
src/Components/SharedComponents/EmptyAccount.js
src/Components/StatusCard/StatusCard.js
src/Messages.js
src/Routes/Signatures/Signatures.js

Adds a link to the documentation in the StatusCard component.  The link appears whether or not there was malware found, as per the screenshots:

feat(RHINENG-2253): Add link to documentation in StatusCard

---

src/Components/SigDetailsTable/SigDetailsTable.js
src/operations/queries.js

Before this PR, you could only filter the SignatureDetails page by name, and there were no filter chips:
With this PR, you can now also filter by host group name, and there are filter chips for both name and group:

feat(RHINENG-2184): Add group filter and chips to SigDetailsPage

---

src/Components/SysTable/hooks.js

On stage, the osFilter is an array of strings and it works with our current implementation:
On prod, the osFilter is an array of objects and breaks our current implementation:
This PR allows our SysTable component to work with with either an array of strings or objects.  This doesn't feel like the right way to fix this, but its just a temporary workaround until we can work out a more permanent solution (which may require changes to the backend).

fix(RHINENG-2708): Temporarily fixes broken OS filter in prod

---

src/Components/StatusCard/StatusCard.js
src/Routes/Signatures/Signatures.js

Part of: https://issues.redhat.com/browse/RHINENG-1217
> Signatures page: Status card should have only one loader each, but has two

Update Status Card loading state

---

src/Components/SigDetailsTable/SigDetailsTable.js
src/Components/SysTable/hooks.js
src/operations/queries.js

Before this PR, filtering the SigDetailsTable hosts by multiple groups returned no results (because the backend didn't support it):
The backend has been recently updated and supports it now, so filtering SigDetailsTable hosts by multiple groups works.  This PR changes the GraphQL query / variables sent to the backend for filtering by multiple groups:

fix(RHINENG-2647): Filter affectedHostsList by multiple groups

---

config/plugins.js
config/prod.webpack.config.js

Not really sure it its going to fix the error, but I notice that malware doesn't have this config plugin option but other apps (eg Advisor, Inventory) seem to have it.

fix: Address the RootApp Sentry error in stage

---

src/Components/CodeEditor/CodeEditor.js
src/Components/SigTable/helper.js

Part of: https://issues.redhat.com/browse/RHINENG-1217
> System detail page and Signature detail page: Expandable section: Downloaded file has some timestamp in the name, it would be more useful if it was named after the system and signature
Fixed according to the UX file naming conventions: https://docs.google.com/document/d/1-SO02nTHuQE9FLz48uCrHnnyDs_bYKzfcmC2ztQAiWs/edit
Previous filename: `1698434121672.txt`
Updated filename: `malware-detection_signature--2023-10-27_19-17-38-UTC.txt`

Set filename when downloading signature

---

src/Routes/Signatures/Details.js
src/Routes/Signatures/Signatures.js
src/Routes/Systems/Details.js
src/Routes/Systems/Systems.js

Resolves: https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868). I have removed the title suffix "Red Hat Insights". Now it will be added by chrome app: https://github.com/RedHatInsights/insights-chrome/commit/64ccf6a190136949911757171d4f2062d02c5235

chore(RHINENG-9387): update page titles

---

.travis.yml

use focal dist and node 18 in travis. It fixes the failing cypress tests in  https://github.com/RedHatInsights/malware-detection-frontend/pull/120

chore: use focal dist and node 18 in travis

---

config/setupTests.js
package.json
src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/helpers.js
src/Messages.js
src/operations/queries.js

This PR adds filtering on "Status" and "Matched status" for the Signature Details and System Details tables, respectively. Both sets of filters apply the same filters to the 2 different tables.
The filters apply both to the systems and signatures that appear in the table, as well as the matches that appear when expanding the system or signature.
To test:
- Go to the Signatures Page
- Click a signature to go to the signature details page Expand a system on the signature details table
- Note the match statuses for the given system
- Apply a status/matched status filter and see updated data Do the same for the Systems Page
Note on how filters should work:
If a signature/system has 1 "Not reviewed" match, 1 "In review" match, and 1 "Resolved" match, then a filter of `IN_REVIEW` would show the …

feat(RHINENG-10987): Add status filters

---

src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
src/Components/TableComponents/DropdownBasic.js
src/Components/TableComponents/NewMatchesTable.js
src/Components/TableComponents/NewMatchesTableRow.js
src/Components/TableComponents/TextInputBasic.js
src/Components/constants.js
src/Components/helpers.js
src/Utilities/Hooks.js

This PR adds functionality to delete a single match detail line as well as multiple match details across multiple systems/signatures.
To test:
- Navigate to Malware
- Navigate to Signatures/Systems
- Click on a Signature/System
- Expand any number of rows with Matches
- Use delete functionality
To test single delete:
- Find a match in the table nested inside of the expanded row
- Click the kebab on the far right of the row
- Click "Delete match"
The table should show loading rows and then refresh with the match removed and all previously expanded rows still expanded. The parent table will also refresh in the background without loading rows and you should see the "New matches" and "Total matches" values update to reflect the deletion you just made.
To test bulk delete:
- Select any number …

feat(RHINENG-10989): Add delete match

---

src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
src/Components/TableComponents/DropdownBasic.js
src/Components/TableComponents/NewMatchesTable.js
src/Components/TableComponents/NewMatchesTableRow.js
src/Components/TableComponents/NewMatchesTableRow.test.js
src/Components/TableComponents/TextInputBasic.js
src/Utilities/Hooks.js

Disable functionality and block edit and delete features when a user doesn't have edit permissions
To test:
- Set malware write permissions to false.
- Navigate to Signatures->Signature details and Systems->System details
- Expand a row with new matches
The following should be disabled:
- Checkboxes
- Status dropdown
- Text field for notes
- The "Delete matches" option in the kebab on the parent table toolbar
The row kebab should not be visible at all.

feat(RHINENG-11758): disable delete and edit without perms

---

src/Components/TableComponents/NewMatchesTable.js

To test:
- Expand an affected system/matched signature
You will see that the column headers are gone. This PR adds them back in.

fix(RHINENG-11797): Fix missing column headers NewMatchesTable

---

src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SysDetailsTable/NewSysDetailsTable.js

Total matches column: Remove the link from the number & make the text black
- Remove the link
- Make the text black
To test:

feat(RHINENG-11794): remove link from total matches column

---

src/Components/SigDetailsTable/Columns.js

This PR resizes the Signature Details Table to avoid truncating column headers on smaller resolution screens. The Systems Details Table seems to be okay.
To test:
Display on a smaller screen and see how many of the column headers beging to truncate.

chore(RHINENG-11795): Resize columns SigDetailsTable

---

src/Components/TableComponents/MatchedDateColumn.js
src/Components/TableComponents/NewMatchesTableRow.test.js
src/Components/helpers.js

When a match is older than 30 days, the Dates matched cells in the NewMatchesTable should not show the blue notification bell icon, even if the status of that match is still "NOT_REVIEWED".
We will need to wait for the backend api to return a `newMatchCount` to properly update the "New Matches" column counts for affected systems and matched signatures.
To test:
- Expand an affected system/matched signature
See that dates older than 30 days do not have the bell icon even when they have a status of Not reviewed. For a code review, you'll need to force an older date in the code to get the desired result.

feat(RHINENG-11792): No bellIcon when older than 30 days

---

src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SigDetailsTable/__tests__/sigDetailsTable.fixtures.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
src/Components/SysDetailsTable/__tests__/sysDetailsTable.fixtures.js
src/Components/TableComponents/MatchedDateColumn.js

New matches column: Remove the Bell icon when the number is 0 AND make the number gray
Remove the bell icon next to 0
Make the 0 text gray
To test:
See that a system with more than 0 new matches shows a blue bell icon with the number of new matches. If it has 0 new matches, then the bell icon will not be visible and the 0 will be gray.
In addition, if you expand an affected system or matched signature, the dates matched column should show a blue bell icon with the date text in black.

feat(RHINENG-11793): No bell icon when new matches 0

---

src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
src/Components/TableComponents/NewMatchesTable.js

Description of Problem
When you apply any filter, sort or pagination change to the Signature Details or System Details tables, the tables don't refetch the data.
How reproducible
100%
Steps to Reproduce
- Navigate to Malware Signatures/Systems
- Click on a Signature or System to go to details table
- Apply any filter, sort or page change
Actual Behavior
The changed data isn't applied to the table
Expected Behavior
Filters, sorting and pagination should change the table

fix(RHINENG-11822): proper table fetch with filtering

---

src/operations/queries.js

This PR simply adds a sort to the query for HITS_TABLE. It sets a descending sort by match date. We aren't currently offering the ability to change the sort, so for now it will remain default.

feat(RHINENG-11791): New matches table sort by date

---

src/Components/SigDetailsTable/Columns.js
src/Components/SigDetailsTable/NewSigDetailsTable.js
src/Components/SigDetailsTable/SigDetailsTableBody.js
src/Components/SigDetailsTable/__tests__/NewSigDetailsTable.tests.js
src/Components/SysDetailsTable/Columns.js
src/Components/SysDetailsTable/NewSysDetailsTable.js
src/Components/SysDetailsTable/SysDetailsTableBody.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js
src/Components/TableComponents/DetailsTableHeader.js
src/Components/TableComponents/DetailsTableRow.js
src/Components/TableComponents/NewMatchesTable.js
src/Utilities/Hooks.js

**Description of Problem**
Assume you have at least 2 Affected systems/Matched signatures for a given Signature/System. If you expand both Affected systems/Matched signatures and then delete every match in the nested table using the checkboxes and bulk delete feature, you will see a failure when the table tries to reload.
**How reproducible**
100%
**Steps to Reproduce**
- Go to Malware and click Signatures/Systems
- Select a signature/system with at least 2 affected systems/matched signatures
- Expand both affected systems/matched signatures
- Use the checkboxes to select every match on the affected system/matched signature at the top level
- Use bulk delete to delete all of the matches
**Actual Behavior**
The top affected system/matched signature is removed and the second one moves in …

fix(RHINENG-11860): Fix bulk deleting all matches

---

src/Components/TableComponents/NewMatchesTableRow.js
src/Components/TableComponents/__tests__/NewMatchesTable.tests.js
src/Components/TableComponents/__tests__/NewMatchesTableRow.test.js

If I change status of match from Not Reviewed to another status the 'New Matches"  count should be updated without refreshing browser. Similarly if status is set to Not Reviewed the count should be incremented

fix(RHINENG-11865): Update new match count

---

src/Components/SysDetailsTable/Columns.js
src/Components/SysDetailsTable/__tests__/NewSysDetailsTable.tests.js

Removing the "Last status" column from the Matched signatures table.

fix(RHINENG-11872): Remove "Last status" column

---

src/Components/constants.js
src/Components/helpers.js

To test:
- Click on a signature/system
- Expand an affected system/matched signature
From here you should be able to expand the dropdown in the status column and see the On hold status updated from On-hold. You should also see it in the toolbar filter for Status.

Update On-hold to On hold

---

src/Components/SysTable/SysTable.js
src/Components/SysTable/constants.js
src/Components/SysTable/constants.test.js
src/operations/queries.js

The last status column was tied to the hasMatch data element. 
With this change the last status column is tied to the lastStatus data element.

System Page: use lastStatus instead of hasMatch for last status column

---

src/Components/SigTable/SigTable.js
src/Components/SigTable/helper.js
src/operations/queries.js

The signature page's last status column is now tied to the lastStatus data element. This means it will only consider the most recent upload from each system.

Switch Sig page to lastStatus instead of hasMatch
